# Generated by Django 5.0.6 on 2024-07-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_news_options_news_shop_sizes_news_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='shop_sizes',
            field=models.CharField(choices=[('S', 'X large'), ('S', 'Large'), ('S', 'Small'), ('M', 'Medium')], default='S', max_length=2),
        ),
    ]
