# Generated by Django 4.2.15 on 2024-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_news_shop_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='shop_sizes',
            field=models.CharField(choices=[('L', 'Large'), ('Xl', 'X large'), ('S', 'Small'), ('M', 'Medium')], default='M', max_length=2, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=2, verbose_name='Просмотры'),
        ),
    ]
